import { startRegistration } from "@simplewebauthn/browser";
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import './App.css';
import LiveLog, { useLiveLog } from './LiveLog';
import ThemeSelector from './ThemeSelector';

function Recovery() {
  const [username, setUsername] = useState("");
  const [recoveryCode, setRecoveryCode] = useState("");
  const [status, setStatus] = useState<{ message: string; type: 'success' | 'error' | '' }>({ message: '', type: '' });
  const [isLoading, setIsLoading] = useState(false);
  const navigate = useNavigate();
  const { logs, addLog, clearLogs } = useLiveLog();

  const recoverAccount = async () => {
    if (!username.trim() || !recoveryCode.trim()) {
      setStatus({ message: 'Please enter username and recovery code', type: 'error' });
      return;
    }

    setIsLoading(true);
    setStatus({ message: '', type: '' });
    clearLogs();
    // Log the recovery process in detail for educational purposes
    addLog('>>> ACCOUNT RECOVERY <<<', 'info')
    addLog(`Username: ${username}`, 'info')
    addLog(`Recovery code: ${recoveryCode.substring(0, 4)}****`, 'info')

    try {
      addLog('Phase 1: Verify Recovery Code', 'info')
      addLog('POST /recover', 'info')
      addLog('Connecting to backend API...', 'waiting')

      const response = await fetch("http://localhost:5001/recover", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username, recovery_code: recoveryCode }),
      });

      const result = await response.json();

      //  Detailed logging of the verification process
      if (!response.ok) {
        addLog('Response: 401 Unauthorized', 'error')
        addLog('Recovery code verification failed', 'error')
        throw new Error(result.error || 'Recovery failed');
      }

      // Simulate detailed backend operations for educational purposes
      addLog('Response: 200 OK', 'success')
      addLog('Code Verification', 'info')
      addLog('SELECT * FROM recovery_codes', 'info')
      addLog(`WHERE user_id = (user: ${username})`, 'info')
      addLog('Hashing provided code with SHA-256...', 'info')
      addLog('Comparing hash with stored hashes...', 'info')
      addLog('Recovery code verified', 'success')
      addLog(`Codes remaining: ${result.codes_remaining}`, 'info')
      addLog('Phase 2: Delete Used Code', 'info')
      addLog('DELETE FROM recovery_codes', 'info')
      addLog('WHERE code_hash = (used code)', 'info')
      addLog('Recovery code invalidated (single-use)', 'success')
      addLog('Phase 3: Register New Passkey', 'info')
      addLog('Challenge generated by server', 'success')
      addLog(`Challenge: ${result.options.publicKey.challenge.substring(0, 24)}...`, 'info')
      addLog('Invoking WebAuthn API...', 'waiting')
      addLog('navigator.credentials.create()', 'info')
      addLog('Awaiting user verification...', 'waiting')

      const credentials = await startRegistration(result.options.publicKey);   
      addLog('User verified successfully', 'success')
      addLog('New credential created', 'success')
      addLog(`Credential ID: ${credentials.id.substring(0, 20)}...`, 'info')
      addLog('Phase 4: Store New Credential', 'info')
      addLog('POST /register/finish', 'info')
      addLog('Sending credential to server...', 'waiting')

      const finishResponse = await fetch("http://localhost:5001/register/finish", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username, credential: credentials }),
      });

      // Detailed logging of the registration process
      if (!finishResponse.ok) {
        addLog('Response: 400 Bad Request', 'error')
        throw new Error('Failed to register new passkey');
      }

      // Simulate detailed backend operations for educational purposes
      addLog('Response: 200 OK', 'success')
      addLog('Attestation verified', 'success')
      addLog('INSERT INTO credentials...', 'info')
      addLog('New passkey stored in PostgreSQL', 'success')
      addLog('>>> RECOVERY COMPLETE <<<', 'success')
      addLog(`Welcome back, ${username}!`, 'success')
      addLog(`Remaining recovery codes: ${result.codes_remaining}`, 'info')
      addLog('Redirecting to login...', 'info')

      setStatus({ 
        message: `Recovery successful! You have ${result.codes_remaining} recovery codes left.`, 
        type: 'success' 
      });
      
      // Redirect to login after 2 seconds
      setTimeout(() => navigate('/'), 2000);
    } catch (error: unknown) {
      console.error(error);
      addLog('>>> RECOVERY FAILED <<<', 'error')
      const errorMessage = error instanceof Error ? error.message : 'Recovery failed';
      addLog(`Error: ${errorMessage}`, 'error')
      setStatus({ message: errorMessage, type: 'error' });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="container">
      <ThemeSelector />
      <div className="card-wide">
      <div className="card-header">
        <div className="icon">🔑</div>
        <h1>Account Recovery</h1>
        <p className="subtitle">Use a recovery code to register a new passkey</p>
      </div>

        <div className="card-body">
          {/* Left panel - Instructions */}
          <div className="panel education-panel">
            <h3>📋 Recovery Steps</h3>
            <div style={{ fontSize: '11px', color: 'var(--text-secondary)' }}>
              <p style={{ marginBottom: '10px' }}><strong style={{ color: 'var(--text-primary)' }}>
                1.</strong> Enter your usernam
                </p>
              <p style={{ marginBottom: '10px' }}><strong style={{ color: 'var(--text-primary)' }}>
                2.</strong> Enter one of your 8 recovery codes
                </p>
              <p style={{ marginBottom: '10px' }}><strong style={{ color: 'var(--text-primary)' }}>
                3.</strong> Register a new passkey
                </p>
              <p style={{ marginBottom: '15px' }}><strong style={{ color: 'var(--text-primary)' }}>
                4.</strong> Login with your new passkey
                </p>
            </div>
            <hr style={{ borderColor: 'var(--border-color)', opacity: 0.3, margin: '15px 0' }} />
            <h3>⚠️ Important</h3>
            <p style={{ fontSize: '11px', color: 'var(--text-secondary)', marginBottom: '8px' }}>
              • Each recovery code can only be used once
              </p>
            <p style={{ fontSize: '11px', color: 'var(--text-secondary)', marginBottom: '8px' }}>
              • Format: XXXX-XXXX (e.g., A1B2-C3D4)
              </p>
            <p style={{ fontSize: '11px', color: 'var(--text-secondary)', marginBottom: '15px' }}>
              • Contact admin if you have no codes left
              </p>
            <button onClick={() => navigate('/')} className="btn-secondary">Back to Login</button>
          </div>
          {/* Center panel - Recovery form */}
          <div className="panel auth-panel">
        <div className="form">
          <input
            type="text"
            placeholder="Username"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            disabled={isLoading}
          />
          <input
            type="text"
            placeholder="Recovery code (e.g. A1B2-C3D4)"
            value={recoveryCode}
            onChange={(e) => setRecoveryCode(e.target.value.toUpperCase())}
            disabled={isLoading}
          />
          
          <button onClick={recoverAccount} disabled={isLoading} className="btn-primary">
            {isLoading ? 'Please wait...' : 'Recover Account'}
          </button>
        </div>

        {status.message && (
          <div className={`status ${status.type}`}>
            {status.message}
          </div>
        )}
      </div>
          {/* Right panel - Live Log */}
          <div className="panel log-panel">
            <LiveLog logs={logs} />
          </div>
        </div>
      </div>
    </div>
  );
}

export default Recovery;